backend:
  name: "git-gateway"
  branch: "master"
  
media_folder: "static/images"
public_folder: "../../static/images"

collections:
      - name: phoneDisplayBlock
        preview: false
        label: "Phone Display Block"
        folder: "content/phoneDisplayBlock"
        create: true
        slug: "{{slug}}"
        filename: "{{fields.title}}.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "description", label: "Description", widget: "string" }
          - { name: "phone_image", label: "Phone Image", widget: image }
          - { name: "icon_image", label: "Icon Image", widget: image }
          - { name: "body", label: "Body", widget: "markdown" }

      - name: review-card
        preview: false
        label: "Review Card"
        folder: "content/reviewCard"
        create: true
        slug: "{{slug}}"
        filename: "{{fields.author}}.md"
        fields:
          - { name: "filename", label: "Filename", widget: "hidden", default: "display" }
          - { name: "author", label: "Author", widget: "string" }
          - { name: "designation", label: "Designation", widget: "string" }
          - { name: "photo", label: "Photo", widget: "image" }
          - { name: "review", label: "Review", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }

      - name: phone_block
        preview: false
        label: "Phone Block"
        folder: "content/phoneBlock"
        create: true
        slug: "{{slug}}"
        filename: "{{fields.filename}}.md"
        fields:
          - { name: "filename", label: "Filename", widget: "hidden", default: "display" }
          - { name: "display_picture", label: "Display Picture", widget: image }
          - { name: "body", label: "Body", widget: "markdown" }
        



